#!/bin/python3

import sys


n = int(input().strip())
arr = [int(arr_temp) for arr_temp in input().strip().split(' ')]
i = n - 1
temp = ""
while(i >= 0):
    temp = temp + str(arr[i]) + " "
    i = i - 1
print(temp)
